### PR TITLE
async logging, start logging to file

### PR DESCRIPTION
**Pull request by laur89**
I wouldn't squash these 2 commits, as they demonstrate two separate ways of making log4j2 logging async.

### CODE REVIEW

**Comment by laur89** [comment]
If you'd prepare to keep config as-is and make file-logging opt-in via sys config, leave a note.

**Comment by laur89** [comment]
> Also, you've removed the _shutdownhook_ config

https://github.com/anthonyraymond/joal/pull/189/files#diff-8ff88692f6f1c189efcc2d347464c74683dc25dcd63bba9359b8820a55f06a64R14

> why do you want to introduce aync logging in an already high asynchronous app

I titled the PR bit wrong - main bit is adding file logging.

**Comment by anthonyraymond** [comment]
Actually there is already a wiki for that https://github.com/anthonyraymond/joal/wiki/Redirect-log-to-file

**Comment by laur89** [comment]
Note my change doesn't modify the hook either. But considering the wiki it's ok to close the PR

**Comment by anthonyraymond** [comment]
Woops i've missread the code 😄 indead the hook was still here.

**Pull request closed without merging**
