### PR TITLE
Create qbittorrent-4.3.0.client

### PR DESCRIPTION
**Pull request by JourneyOver**
New update released for qbittorrent.

I updated the qbittorrent client update detector script as well and added a bit of code so that it would go in and create the actual client file as well. (I added a qbittorrent-0.0.0.client into a blankclients folder which the script will grab and copy+rename to the correct version into the clients folder along with also editing the peer id and the user agent) 

the script update is mainly mostly for me so that I can just quickly make the file without to much hassle anymore xD so if you don't want the updated script file I can revert it.

### CODE REVIEW

**Comment by JourneyOver** [comment]
oh also the peerid prefix generator might have changed as I had to end up changing it to `lt` instead of `libt` .. not sure if anyone else really changed though as what it gave was `key : qBittorent is using libtorrent => Libtorrent generate keys matching regex pattern [0-F]{8} (uppercased)`

**Comment by JourneyOver** [comment]
> qBittorrent v4.3.0.1 was released.
> This is a minor release to address crashes on Windows related to torrents with URL seeds (HTTP Sources in the qbittorrent window). These crashes were exposed due to boost 1.74. Boost 1.73 doesn't have this problem. However, libtorrent also fixed the issue on their end so the Windows installers use the newer libtorrent code.
> The rest of the release is almost the same as v4.3.0 (see changelog). Since other platforms weren't affected only Windows builds will be made available for this version.

**Comment by anthonyraymond** [comment]
Hey :) thanks. perfect as usual 👍 

I'd rather not add the "blanks" clients, can you remove them from the pull request (and also revert the changes in the bash script (except the libt to lt) ?

Thanks in advance and sorry for the delay i'm pretty busy atm.

**Comment by JourneyOver** [comment]
> I'd rather not add the "blanks" clients, can you remove them from the pull request (and also revert the changes in the bash script (except the libt to lt) ?
> 
> Thanks in advance and sorry for the delay i'm pretty busy atm.

That's not a problem so yea I can do that, I'll just keep a branch on my fork with the bash/blank client file changes so I can easily make clients quickly while this PR (and future) will be just the normal client files and the libt to lt change in the bash script.

**Comment by JourneyOver** [comment]
Done

**Pull request merged**
